wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1649740884
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      3:
      - 1
      4: 3.7.12
      5: 0.12.11
      6: 4.18.0
      8:
      - 1
      - 5
